BaseUrl = "https://blog.hika69.com/"
LanguageCode = "ja"
Title = "hikarock blog"
paginate = 10
Copyright = "&copy; 2017 hikarock"
canonifyurls = true

[indexes]
  tag = "tags"

[permalinks]
  post = "/blog/:year/:month/:day/:filename/"

[params]
  # description = ""
  # metadescription = ""
  cover = "images/cover.jpg"
  author = "hikarock"
  authorlocation = "Tokyo, Japan"
  authorwebsite = "https://hika69.com"
  bio= "街に詳しい。"
  logo = "images/logo.png"
  githubName = "hikarock"
  twitterName = "hika69"
  googleAnalyticsUserID = "UA-16254980-7"
  hideHUGOSupport = false
  customHeaderPartial = "customHeader.html"
  customFooterPartial = "customFooter.html"

